#!/bin/bash
# Script to reorganize ANE research directories

ANALYSIS_DIR="/Users/longxia/Projects/GPUPeek/src/metal/Sources/MetalBenchmark/Benchmarks/Analysis"
DOCS_DIR="/Users/longxia/Projects/GPUPeek/docs"

echo "=== ANE Research Reorganization Script ==="
echo "Running at: $(date)"

# Create summary index
SUMMARY_FILE="$DOCS_DIR/ANE_RESEARCH_INDEX.md"

echo "# ANE Research Index" > "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"
echo "Generated: $(date)" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"
echo "## Research Categories" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

# Categories
declare -a CATEGORIES=(
    "Performance:ANEPerformanceMaximization,ANEThroughputScaling,ANEComputeUnitThroughputEfficiency"
    "Memory:ANEMemoryBandwidth,ANEMemoryLatency,ANEMemoryCoalescing,ANEMemoryPrefetching"
    "Precision:ANEBFloat16Precision,ANEQuantizationINT8Inference,ANEWeightOnlyQuantization"
    "Operations:ANEAttentionPopcountBitwise,ANEActivationFunctions,ANENormalizationOperations"
    "Optimization:ANEKernelFusion,ANEAsyncCopyMemoryTransferOptimization,ANEDataLocalityOptimization"
)

for category in "${CATEGORIES[@]}"; do
    name="${category%%:*}"
    items="${category#*:}"
    echo "### $name" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
    IFS=',' read -ra ITEMS <<< "$items"
    for item in "${ITEMS[@]}"; do
        dir="$ANALYSIS_DIR/$item"
        if [ -d "$dir" ]; then
            has_swift=$(find "$dir" -name "*.swift" 2>/dev/null | wc -l)
            has_research=$(find "$dir" -name "RESEARCH.md" 2>/dev/null | wc -l)
            has_log=$(find "$dir" -name "LOG.txt" 2>/dev/null | wc -l)
            status="❌"
            [ "$has_swift" -gt 0 ] && [ "$has_research" -gt 0 ] && status="✅"
            echo "- $status $item (Swift: $has_swift, Research: $has_research, Log: $has_log)" >> "$SUMMARY_FILE"
        fi
    done
    echo "" >> "$SUMMARY_FILE"
done

# Count totals
total_dirs=$(ls -d "$ANALYSIS_DIR"/ANE* 2>/dev/null | wc -l)
with_swift=$(find "$ANALYSIS_DIR" -name "*.swift" -type f 2>/dev/null | wc -l)
with_research=$(find "$ANALYSIS_DIR" -name "RESEARCH.md" -type f 2>/dev/null | wc -l)
with_log=$(find "$ANALYSIS_DIR" -name "LOG.txt" -type f 2>/dev/null | wc -l)

echo "## Summary Statistics" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"
echo "| Metric | Count |" >> "$SUMMARY_FILE"
echo "|--------|-------|" >> "$SUMMARY_FILE"
echo "| Total ANE Research Dirs | $total_dirs |" >> "$SUMMARY_FILE"
echo "| With Swift Code | $with_swift |" >> "$SUMMARY_FILE"
echo "| With RESEARCH.md | $with_research |" >> "$SUMMARY_FILE"
echo "| With LOG.txt | $with_log |" >> "$SUMMARY_FILE"

# Find incomplete benchmarks (no Swift or no RESEARCH.md)
echo "" >> "$SUMMARY_FILE"
echo "## Incomplete Benchmarks" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

incomplete=""
for dir in "$ANALYSIS_DIR"/ANE*; do
    if [ -d "$dir" ]; then
        name=$(basename "$dir")
        has_swift=$(find "$dir" -name "*.swift" 2>/dev/null | wc -l)
        has_research=$(find "$dir" -name "RESEARCH.md" 2>/dev/null | wc -l)
        if [ "$has_swift" -eq 0 ] || [ "$has_research" -eq 0 ]; then
            incomplete="$incomplete- $name (Swift: $has_swift, Research: $has_research)\n"
        fi
    fi
done

if [ -z "$incomplete" ]; then
    echo "All benchmarks are complete! ✅" >> "$SUMMARY_FILE"
else
    echo -e "$incomplete" >> "$SUMMARY_FILE"
fi

echo "" >> "$SUMMARY_FILE"
echo "## Recent Updates" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"
find "$ANALYSIS_DIR" -name "RESEARCH.md" -type f -mtime -7 2>/dev/null | while read f; do
    dir=$(dirname "$f")
    name=$(basename "$dir")
    mtime=$(stat -f "%Sm" -t "%Y-%m-%d" "$f" 2>/dev/null || stat -c "%y" "$f" 2>/dev/null | cut -d' ' -f1)
    echo "- $name (updated: $mtime)" >> "$SUMMARY_FILE"
done

echo "" >> "$SUMMARY_FILE"
echo "---" >> "$SUMMARY_FILE"
echo "*Auto-generated by GPUPeek research reorganization script*" >> "$SUMMARY_FILE"

echo "Summary written to: $SUMMARY_FILE"
echo "Total dirs: $total_dirs, With Swift: $with_swift, With Research: $with_research"
